x = 6
for numbers in range(1,6):
    print (x - numbers)
print ("Blastoff!")
print ("  ...")
print ("  ...")
print ("  ...")
print ("  ...")
print ("  ...")
print ("  ...")
print ("  ...")
print ("  ...")
print ("  ...")
print ("  ...")
print ("*explosion*")
print ("  /\\")
print (" |  |")
print (" |  |")
print (" |  |")
print (" /  \\")
print ("|    |")
print ("|    |")
print ("------")
print (":(")
